apiVersion: v1
kind: PersistentVolume
metadata:
    name: calibre-books
    namespace: calibre
spec:
    capacity:
        storage: 8Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    storageClassName: local-path
    hostPath:
        path: /var/data/calibre/books/
