apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: calibre-books
    namespace: calibre
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 8Gi
    storageClassName: local-path
    volumeName: calibre-books
